/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface WebtrainingButton {
        "primary": boolean;
        "value": string;
    }
    interface WebtrainingPersonalCard {
        "firstName": string;
        "lastName": string;
        "photo": string;
        "resume": string;
        "rol": string;
    }
    interface WebtrainingSidebar {
        "open": () => Promise<void>;
        "sidebarOpen": boolean;
    }
    interface WebtrainingSidebarOption {
    }
    interface WebtrainingVideoPlayer {
        "provider": string;
        "source": any;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLWebtrainingButtonElement extends Components.WebtrainingButton, HTMLStencilElement {
    }
    var HTMLWebtrainingButtonElement: {
        prototype: HTMLWebtrainingButtonElement;
        new (): HTMLWebtrainingButtonElement;
    };
    interface HTMLWebtrainingPersonalCardElement extends Components.WebtrainingPersonalCard, HTMLStencilElement {
    }
    var HTMLWebtrainingPersonalCardElement: {
        prototype: HTMLWebtrainingPersonalCardElement;
        new (): HTMLWebtrainingPersonalCardElement;
    };
    interface HTMLWebtrainingSidebarElement extends Components.WebtrainingSidebar, HTMLStencilElement {
    }
    var HTMLWebtrainingSidebarElement: {
        prototype: HTMLWebtrainingSidebarElement;
        new (): HTMLWebtrainingSidebarElement;
    };
    interface HTMLWebtrainingSidebarOptionElement extends Components.WebtrainingSidebarOption, HTMLStencilElement {
    }
    var HTMLWebtrainingSidebarOptionElement: {
        prototype: HTMLWebtrainingSidebarOptionElement;
        new (): HTMLWebtrainingSidebarOptionElement;
    };
    interface HTMLWebtrainingVideoPlayerElement extends Components.WebtrainingVideoPlayer, HTMLStencilElement {
    }
    var HTMLWebtrainingVideoPlayerElement: {
        prototype: HTMLWebtrainingVideoPlayerElement;
        new (): HTMLWebtrainingVideoPlayerElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "webtraining-button": HTMLWebtrainingButtonElement;
        "webtraining-personal-card": HTMLWebtrainingPersonalCardElement;
        "webtraining-sidebar": HTMLWebtrainingSidebarElement;
        "webtraining-sidebar-option": HTMLWebtrainingSidebarOptionElement;
        "webtraining-video-player": HTMLWebtrainingVideoPlayerElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface WebtrainingButton {
        "primary"?: boolean;
        "value"?: string;
    }
    interface WebtrainingPersonalCard {
        "firstName"?: string;
        "lastName"?: string;
        "photo"?: string;
        "resume"?: string;
        "rol"?: string;
    }
    interface WebtrainingSidebar {
        "sidebarOpen"?: boolean;
    }
    interface WebtrainingSidebarOption {
    }
    interface WebtrainingVideoPlayer {
        "provider"?: string;
        "source"?: any;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "webtraining-button": WebtrainingButton;
        "webtraining-personal-card": WebtrainingPersonalCard;
        "webtraining-sidebar": WebtrainingSidebar;
        "webtraining-sidebar-option": WebtrainingSidebarOption;
        "webtraining-video-player": WebtrainingVideoPlayer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "webtraining-button": LocalJSX.WebtrainingButton & JSXBase.HTMLAttributes<HTMLWebtrainingButtonElement>;
            "webtraining-personal-card": LocalJSX.WebtrainingPersonalCard & JSXBase.HTMLAttributes<HTMLWebtrainingPersonalCardElement>;
            "webtraining-sidebar": LocalJSX.WebtrainingSidebar & JSXBase.HTMLAttributes<HTMLWebtrainingSidebarElement>;
            "webtraining-sidebar-option": LocalJSX.WebtrainingSidebarOption & JSXBase.HTMLAttributes<HTMLWebtrainingSidebarOptionElement>;
            "webtraining-video-player": LocalJSX.WebtrainingVideoPlayer & JSXBase.HTMLAttributes<HTMLWebtrainingVideoPlayerElement>;
        }
    }
}
